# This is a basic workflow to help you get started User Input
# Dec 6, 2021

name: UserInput
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Define env name
        required: true
        default: prod
      branch:
        description: Define branch name
        required: true
        default: master
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Env: ${{ github.event.inputs.environment }}" 
          echo "Branch: ${{ github.event.inputs.branch }}"
