#This is a basic workflow to connect to EC2 Instance
#Owner:- Vasitum Devops Team
#Date:- Dec 6, 2021

name: vasitumdevops 
on: 
  workflow_dispatch:
    inputs:
      repo:
        description: 'Define Repository name'     
        required: true
        default: 'my-project'
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'
      environment:
        type: choice
        description: Choose environment
        options: 
        - TEST
        - DEV
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.repository.owner.login }}/${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.branch }}
        
    - name: Deploy to EC2
      if: ${{ github.event.inputs.environment == 'TEST' }}
      env:
        KEY: secrets.${{ github.event.inputs.environment }}_ACCESS_KEY
        ACCESS_KEY: '${{ secrets.TEST_ACCESS_KEY  }}'
        HOSTNAME: '${{ secrets.TEST_HOSTNAME  }}'
        USERNAME: '${{ secrets.USERNAME  }}'        
      run: >
      
        echo "Env: ${{ github.event.inputs.environment }}" 
        
        echo "Branch: ${{ github.event.inputs.branch }}" 
        
        echo "Repo: ${{ github.event.inputs.repo }}" 
        
        echo "${KEY}"
                
        #echo "${ACCESS_KEY}" > access_key && chmod 600 access_key
        
        #scp -o StrictHostKeyChecking=no -i access_key  test.txt ${USERNAME}@${HOSTNAME}:~/
        
        #ssh -o StrictHostKeyChecking=no -i access_key ${USERNAME}@${HOSTNAME} touch test.txt
